[versions]
spotless-plugin = "8.10.1"
gradle-version-plugin = "0.53.0"
shadow-plugin = "8.3.11"
lombok-plugin = "9.5.0"
javalin-lib = "7.2.2"
slf4j-simple-lib = "2.0.7"
h2database-lib = "2.2.220"
hicariCP-lib = "5.0.1"


[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-version-plugin"}
shadow = { id = "com.gradleup.shadow", version.ref = "shadow-plugin"}
lombok = { id = "io.freefair.lombok", version.ref = "lombok-plugin"}


[libraries]
javalin = { module = "io.javalin:javalin", version.ref = "javalin-lib"}
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j-simple-lib"}
hicariCP = { module = "com.zaxxer:HikariCP", version.ref = "hicariCP-lib"}
h2database = { module = "com.h2database:h2", version.ref = "h2database-lib"}
